//! Audit + regression test for `src/grpc/status.rs`
//! `Status::message` length cap (tick #179).
//!
//! Operator's question: "verify max-length enforced, no DoS via
//! huge error message."
//!
//! Audit findings (extends tick #161):
//!
//!   (a) **`MAX_STATUS_MESSAGE_LEN = 8 KiB`** (status.rs:134).
//!       Defense-in-depth cap matching the typical HTTP/2 max
//!       header value limit.
//!
//!   (b) **`Status::new` calls `cap_status_message`**
//!       (status.rs:193-199). This is the central choke point —
//!       every other constructor delegates here.
//!
//!   (c) **`Status::with_details` caps BOTH message AND details**
//!       (status.rs:206-212). Details are bounded at
//!       `MAX_STATUS_DETAILS_LEN = 64 KiB`.
//!
//!   (d) **All 16 shorthand constructors** (cancelled, unknown,
//!       invalid_argument, deadline_exceeded, not_found,
//!       already_exists, permission_denied, resource_exhausted,
//!       failed_precondition, aborted, out_of_range,
//!       unimplemented, internal, unavailable, data_loss,
//!       unauthenticated) are generated by the
//!       `status_constructors!` macro (status.rs:171-184) and
//!       all call `Self::new(...)` — so all 16 inherit the cap.
//!       The macro pattern means a regression to one
//!       constructor would propagate, but it ALSO means any
//!       future hand-rolled constructor must explicitly call
//!       `cap_status_message` or it bypasses the cap.
//!
//!   (e) **`cap_status_message` truncates at UTF-8 char
//!       boundary** (status.rs:152-161). Never panics on
//!       truncation — searches backwards for the last char
//!       boundary at-or-below the cap (br-asupersync-uk2vsg).
//!
//! Regression tests below pin (a)-(e).

use asupersync::bytes::Bytes;
use asupersync::grpc::Status;
use asupersync::grpc::status::{Code, MAX_STATUS_MESSAGE_LEN};

const MAX_DETAILS_LEN: usize = 64 * 1024;

#[test]
fn status_new_caps_oversize_message() {
    // Pin (b): `Status::new(code, msg)` is the central path.
    let oversize = "X".repeat(64 * 1024); // 8x the cap
    let status = Status::new(Code::Internal, oversize);
    assert!(
        status.message().len() <= MAX_STATUS_MESSAGE_LEN,
        "Status::new must cap at MAX_STATUS_MESSAGE_LEN; got {}",
        status.message().len(),
    );
}

#[test]
fn all_shorthand_constructors_cap_oversize_message() {
    // Pin (d): every shorthand constructor inherits the cap
    // via the status_constructors! macro. We exercise all 16
    // shorthand constructors with an oversize message and
    // verify each one truncates to ≤ MAX_STATUS_MESSAGE_LEN.
    let oversize = "Z".repeat(32 * 1024);

    // Use closures so we can iterate over (constructor_name, constructor_fn).
    type Ctor = fn(String) -> Status;
    let constructors: &[(&str, Ctor)] = &[
        ("cancelled", |s| Status::cancelled(s)),
        ("unknown", |s| Status::unknown(s)),
        ("invalid_argument", |s| Status::invalid_argument(s)),
        ("deadline_exceeded", |s| Status::deadline_exceeded(s)),
        ("not_found", |s| Status::not_found(s)),
        ("already_exists", |s| Status::already_exists(s)),
        ("permission_denied", |s| Status::permission_denied(s)),
        ("resource_exhausted", |s| Status::resource_exhausted(s)),
        ("failed_precondition", |s| Status::failed_precondition(s)),
        ("aborted", |s| Status::aborted(s)),
        ("out_of_range", |s| Status::out_of_range(s)),
        ("unimplemented", |s| Status::unimplemented(s)),
        ("internal", |s| Status::internal(s)),
        ("unavailable", |s| Status::unavailable(s)),
        ("data_loss", |s| Status::data_loss(s)),
        ("unauthenticated", |s| Status::unauthenticated(s)),
    ];

    for (name, ctor) in constructors {
        let status = ctor(oversize.clone());
        assert!(
            status.message().len() <= MAX_STATUS_MESSAGE_LEN,
            "Status::{name} must cap at MAX_STATUS_MESSAGE_LEN; got {}",
            status.message().len(),
        );
    }
}

#[test]
fn with_details_caps_both_message_and_details() {
    // Pin (c): with_details applies cap_status_message AND
    // cap_status_details. A regression that capped only one
    // would leave the other channel as a DoS vector.
    let oversize_msg = "M".repeat(16 * 1024);
    let oversize_details_bytes = vec![b'D'; 256 * 1024]; // 4x details cap

    let status = Status::with_details(
        Code::Internal,
        oversize_msg,
        Bytes::from(oversize_details_bytes),
    );

    assert!(
        status.message().len() <= MAX_STATUS_MESSAGE_LEN,
        "with_details message cap not enforced",
    );
    let details_len = status.details().map_or(0, |b| b.len());
    assert!(
        details_len <= MAX_DETAILS_LEN,
        "with_details details cap not enforced; got {details_len} bytes",
    );
}

#[test]
fn status_message_cap_handles_multibyte_utf8_at_boundary() {
    // Pin (e): a multibyte char straddling the cap is truncated
    // at the LAST valid char boundary at-or-below the cap. Never
    // panics, never produces invalid UTF-8.
    //
    // Construct: ASCII fill up to (cap - 2 bytes), then a 4-byte
    // UTF-8 codepoint (😀 = U+1F600 = F0 9F 98 80) so the first
    // 2 bytes of the codepoint sit just before the cap and the
    // last 2 bytes sit just past. The truncation must back up to
    // before the codepoint starts.
    let mut input = "a".repeat(MAX_STATUS_MESSAGE_LEN - 2);
    input.push('😀'); // 4 bytes, straddles the cap
    input.push_str("trailing ascii");

    let status = Status::internal(input);
    let msg = status.message();
    assert!(msg.len() <= MAX_STATUS_MESSAGE_LEN);
    // The result must be valid UTF-8 — re-parse to verify.
    let _ = String::from_utf8(msg.as_bytes().to_vec())
        .expect("truncation preserved UTF-8 char boundary");
    // The truncation happened BEFORE the 4-byte codepoint, so
    // the message contains only the leading "a" run.
    assert!(
        msg.chars().all(|c| c == 'a'),
        "UTF-8-aware truncation must drop the straddling codepoint, \
         leaving only the leading ASCII run",
    );
}

#[test]
fn status_message_cap_does_not_panic_on_huge_input() {
    // Pin (e) extension: 16 MiB input must not panic. Audit-
    // critical: a constructor that allocates O(n) on the input
    // and only THEN truncates would briefly hold a 16 MiB
    // String — that's a soft DoS class. The current
    // implementation receives the String by value (move) and
    // truncates in-place via slice — bounded work.
    let huge = "X".repeat(16 * 1024 * 1024); // 16 MiB
    let status = Status::internal(huge);
    assert!(
        status.message().len() <= MAX_STATUS_MESSAGE_LEN,
        "16 MiB input must cap at 8 KiB",
    );
}

#[test]
fn status_at_exact_cap_passes_through_unchanged() {
    // Pin (a) boundary: a message EXACTLY at MAX_STATUS_MESSAGE_LEN
    // is preserved unchanged (no spurious truncation, no
    // alloc-and-copy when below threshold).
    let exact = "A".repeat(MAX_STATUS_MESSAGE_LEN);
    let status = Status::internal(exact.clone());
    assert_eq!(
        status.message().len(),
        MAX_STATUS_MESSAGE_LEN,
        "at-cap message preserved at full length",
    );
    assert_eq!(status.message(), exact.as_str(), "at-cap content unchanged");
}

#[test]
fn status_below_cap_passes_through_unchanged_no_alloc() {
    // Sanity: a normal-size message is preserved verbatim. A
    // regression that aggressively truncated all messages
    // would break operator-readable error reporting.
    let s = Status::internal("connection lost: peer went away");
    assert_eq!(s.message(), "connection lost: peer went away");
    let ok = Status::ok();
    assert_eq!(ok.message(), "");
}

#[test]
fn details_at_exact_cap_passes_through_unchanged() {
    // Pin (c) boundary: details AT exactly MAX_DETAILS_LEN
    // pass through.
    let at_cap = vec![b'D'; MAX_DETAILS_LEN];
    let status = Status::with_details(Code::Internal, "msg", Bytes::from(at_cap));
    assert_eq!(status.details().map_or(0, |b| b.len()), MAX_DETAILS_LEN);
}

#[test]
fn display_impl_does_not_grow_message_past_cap() {
    // Pin (a) extension: format!("{}", status) doesn't
    // amplify the message bytes. The cap-at-construction
    // means the Display output is bounded at
    // ~MAX_STATUS_MESSAGE_LEN + a few bytes for the
    // "gRPC status <code>: " prefix.
    let oversize = "Y".repeat(64 * 1024);
    let status = Status::internal(oversize);
    let displayed = format!("{status}");
    assert!(
        displayed.len() <= MAX_STATUS_MESSAGE_LEN + 64,
        "Display output bounded by cap + prefix; got {} bytes",
        displayed.len(),
    );
}
