//! Metamorphic conformance harness for `asupersync::trace::gf2`.
//!
//! `trace::gf2` is the GF(2) bitset linear algebra under the persistent
//! homology pipeline (`trace::scoring`, `trace::geodesic`). It has no
//! observable "correct answer" for an arbitrary input matrix — the *oracle
//! problem* — but it does satisfy a dense web of algebraic relations that any
//! correct implementation must preserve. This harness pins those relations.
//!
//! ## Metamorphic relations covered
//!
//! `BitVec` as a vector in the GF(2) vector space `GF(2)^n`:
//! - XOR is an abelian group: closure, commutativity, associativity,
//!   identity (`zeros`), self-inverse (`a^a == 0`), involution (`(a^b)^b==a`).
//! - `xor` (functional) and `xor_assign` (in-place) agree.
//! - Parity: `popcount(a^b) ≡ popcount(a)+popcount(b) (mod 2)`.
//! - Hamming bounds: `||a|-|b|| ≤ popcount(a^b) ≤ |a|+|b|`.
//! - `set`/`clear`/`flip` idempotence and involution.
//! - `pivot == min(ones())`, `highest_bit == max(ones())`,
//!   `count_ones == ones().count()`, `ones()` strictly ascending and bounded.
//! - The four-way equivalence `is_zero ⇔ popcount 0 ⇔ pivot None ⇔ highest None`.
//!
//! `BoundaryMatrix::reduce` (standard left-to-right column reduction):
//! - Determinism (same input → identical reduced matrix).
//! - Dimension preservation.
//! - Pivot uniqueness: distinct non-zero reduced columns have distinct pivots.
//! - Idempotence: reducing an already-reduced matrix changes no pivot.
//! - `pivot_map` round-trips with `column_pivot`.
//! - Rank (= count of non-zero reduced columns) is invariant under column
//!   permutation and under elementary column XORs — because `reduce` is built
//!   from exactly those operations.
//! - Zero columns survive reduction as zero columns.
//! - Duplicating a non-zero column does not raise rank.
//!
//! `persistence_pairs`:
//! - structural well-formedness (in-range indices, unique births, unique
//!   deaths), pair count equals rank, no panic on non-square matrices.
//!
//! All inputs are generated by a deterministic in-test LCG so failures are
//! reproducible from the printed seed; no `proptest` dependency.

#![allow(clippy::needless_range_loop)]
#![allow(clippy::too_many_lines)]

use std::collections::BTreeSet;

use asupersync::trace::{BitVec, BoundaryMatrix};

// ---------------------------------------------------------------------------
// Deterministic generators
// ---------------------------------------------------------------------------

/// SplitMix64 — a small, well-distributed deterministic PRNG. Reproducible
/// across platforms; a failing case is fully described by its seed.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Self(seed.wrapping_add(0x9E37_79B9_7F4A_7C15))
    }

    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Uniform integer in `[0, n)`. `n` must be non-zero.
    fn below(&mut self, n: usize) -> usize {
        (self.next_u64() % n as u64) as usize
    }

    fn bool_with(&mut self, ones_in_64: u32) -> bool {
        (self.next_u64() & 63) < u64::from(ones_in_64)
    }
}

/// Build a `BitVec` of `len` bits, each set with probability `density/64`.
fn gen_bitvec(rng: &mut Rng, len: usize, density: u32) -> BitVec {
    let mut v = BitVec::zeros(len);
    for i in 0..len {
        if rng.bool_with(density) {
            v.set(i);
        }
    }
    v
}

/// Build a `rows x cols` boundary matrix with random entries.
fn gen_matrix(rng: &mut Rng, rows: usize, cols: usize, density: u32) -> BoundaryMatrix {
    let mut m = BoundaryMatrix::zeros(rows, cols);
    for j in 0..cols {
        for i in 0..rows {
            if rng.bool_with(density) {
                m.set(i, j);
            }
        }
    }
    m
}

/// Sizes / seeds swept by the matrix-level relations. Mixes square, wide,
/// and tall shapes plus assorted bit densities.
const MATRIX_CASES: &[(usize, usize, u32)] = &[
    (1, 1, 32),
    (3, 3, 24),
    (5, 5, 20),
    (8, 8, 16),
    (16, 16, 12),
    (32, 24, 10),
    (24, 40, 8),
    (70, 50, 6), // crosses the 64-bit word boundary
    (50, 70, 6),
    (128, 64, 4),
];

const BITVEC_LENS: &[usize] = &[0, 1, 7, 63, 64, 65, 127, 128, 200, 500];

// ---------------------------------------------------------------------------
// Small helpers shared across relations
// ---------------------------------------------------------------------------

fn rank(m: &BoundaryMatrix) -> usize {
    let reduced = m.reduce();
    (0..reduced.matrix.cols())
        .filter(|&j| reduced.matrix.column_pivot(j).is_some())
        .count()
}

fn columns(m: &BoundaryMatrix) -> Vec<BitVec> {
    (0..m.cols()).map(|j| m.column(j).clone()).collect()
}

// ---------------------------------------------------------------------------
// BitVec — GF(2) vector space axioms
// ---------------------------------------------------------------------------

#[test]
fn xor_is_commutative() {
    for &len in BITVEC_LENS {
        for seed in 0..24u64 {
            let mut rng = Rng::new(seed ^ (len as u64) << 8);
            let a = gen_bitvec(&mut rng, len, 24);
            let b = gen_bitvec(&mut rng, len, 24);
            assert_eq!(
                a.xor(&b),
                b.xor(&a),
                "xor not commutative (len={len}, seed={seed})"
            );
        }
    }
}

#[test]
fn xor_is_associative() {
    for &len in BITVEC_LENS {
        for seed in 0..24u64 {
            let mut rng = Rng::new(seed ^ 0xA5 ^ (len as u64) << 8);
            let a = gen_bitvec(&mut rng, len, 20);
            let b = gen_bitvec(&mut rng, len, 20);
            let c = gen_bitvec(&mut rng, len, 20);
            let left = a.xor(&b).xor(&c);
            let right = a.xor(&b.xor(&c));
            assert_eq!(left, right, "xor not associative (len={len}, seed={seed})");
        }
    }
}

#[test]
fn xor_zero_is_identity_and_self_is_inverse() {
    for &len in BITVEC_LENS {
        for seed in 0..24u64 {
            let mut rng = Rng::new(seed ^ 0x3C ^ (len as u64) << 8);
            let a = gen_bitvec(&mut rng, len, 24);
            let zero = BitVec::zeros(len);

            // identity: a ^ 0 == a
            assert_eq!(a.xor(&zero), a, "xor identity (len={len}, seed={seed})");
            // self-inverse: a ^ a == 0
            let self_xor = a.xor(&a);
            assert!(
                self_xor.is_zero(),
                "a^a must be zero (len={len}, seed={seed})"
            );
            assert_eq!(self_xor, zero);
        }
    }
}

#[test]
fn xor_is_an_involution() {
    // (a ^ b) ^ b == a — flipping the same vector twice is the identity.
    for &len in BITVEC_LENS {
        for seed in 0..32u64 {
            let mut rng = Rng::new(seed ^ 0x7E ^ (len as u64) << 8);
            let a = gen_bitvec(&mut rng, len, 22);
            let b = gen_bitvec(&mut rng, len, 22);
            assert_eq!(
                a.xor(&b).xor(&b),
                a,
                "xor involution failed (len={len}, seed={seed})"
            );
        }
    }
}

#[test]
fn xor_assign_agrees_with_functional_xor() {
    for &len in BITVEC_LENS {
        for seed in 0..24u64 {
            let mut rng = Rng::new(seed ^ 0x11 ^ (len as u64) << 8);
            let a = gen_bitvec(&mut rng, len, 20);
            let b = gen_bitvec(&mut rng, len, 20);
            let functional = a.xor(&b);
            let mut in_place = a.clone();
            in_place.xor_assign(&b);
            assert_eq!(
                functional, in_place,
                "xor / xor_assign disagree (len={len}, seed={seed})"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// BitVec — counting / parity invariants
// ---------------------------------------------------------------------------

#[test]
fn popcount_parity_is_additive_under_xor() {
    // popcount(a ^ b) ≡ popcount(a) + popcount(b)  (mod 2)
    for &len in BITVEC_LENS {
        for seed in 0..40u64 {
            let mut rng = Rng::new(seed ^ 0x99 ^ (len as u64) << 8);
            let a = gen_bitvec(&mut rng, len, 24);
            let b = gen_bitvec(&mut rng, len, 24);
            let lhs = a.xor(&b).count_ones() % 2;
            let rhs = (a.count_ones() + b.count_ones()) % 2;
            assert_eq!(lhs, rhs, "xor parity broke (len={len}, seed={seed})");
        }
    }
}

#[test]
fn popcount_under_xor_is_hamming_bounded() {
    // |popcount(a) - popcount(b)| <= popcount(a^b) <= popcount(a)+popcount(b)
    for &len in BITVEC_LENS {
        for seed in 0..32u64 {
            let mut rng = Rng::new(seed ^ 0x42 ^ (len as u64) << 8);
            let a = gen_bitvec(&mut rng, len, 24);
            let b = gen_bitvec(&mut rng, len, 24);
            let pa = a.count_ones();
            let pb = b.count_ones();
            let pc = a.xor(&b).count_ones();
            assert!(
                pc <= pa + pb,
                "upper Hamming bound (len={len}, seed={seed})"
            );
            assert!(
                pc >= pa.abs_diff(pb),
                "lower Hamming bound (len={len}, seed={seed})"
            );
        }
    }
}

#[test]
fn count_ones_equals_ones_iterator_length() {
    for &len in BITVEC_LENS {
        for seed in 0..24u64 {
            let mut rng = Rng::new(seed ^ 0x5B ^ (len as u64) << 8);
            let v = gen_bitvec(&mut rng, len, 24);
            assert_eq!(
                v.count_ones(),
                v.ones().count(),
                "count_ones vs ones() (len={len}, seed={seed})"
            );
        }
    }
}

#[test]
fn ones_iterator_is_strictly_ascending_and_in_range() {
    for &len in BITVEC_LENS {
        for seed in 0..24u64 {
            let mut rng = Rng::new(seed ^ 0x6D ^ (len as u64) << 8);
            let v = gen_bitvec(&mut rng, len, 24);
            let mut prev: Option<usize> = None;
            for idx in v.ones() {
                assert!(idx < len, "ones() index {idx} >= len {len}");
                assert!(v.get(idx), "ones() yielded a clear bit {idx}");
                if let Some(p) = prev {
                    assert!(p < idx, "ones() not strictly ascending: {p} !< {idx}");
                }
                prev = Some(idx);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// BitVec — pivot / highest_bit / is_zero equivalences
// ---------------------------------------------------------------------------

#[test]
fn pivot_and_highest_bit_match_ones_extremes() {
    for &len in BITVEC_LENS {
        for seed in 0..40u64 {
            let mut rng = Rng::new(seed ^ 0x2F ^ (len as u64) << 8);
            let v = gen_bitvec(&mut rng, len, 20);
            let ones: Vec<usize> = v.ones().collect();
            assert_eq!(
                v.pivot(),
                ones.first().copied(),
                "pivot != min(ones) (len={len}, seed={seed})"
            );
            assert_eq!(
                v.highest_bit(),
                ones.last().copied(),
                "highest_bit != max(ones) (len={len}, seed={seed})"
            );
            if let (Some(lo), Some(hi)) = (v.pivot(), v.highest_bit()) {
                assert!(lo <= hi, "pivot must be <= highest_bit");
            }
        }
    }
}

#[test]
fn zero_predicates_are_mutually_consistent() {
    // is_zero ⇔ count_ones()==0 ⇔ pivot()==None ⇔ highest_bit()==None
    for &len in BITVEC_LENS {
        for seed in 0..32u64 {
            let mut rng = Rng::new(seed ^ 0x84 ^ (len as u64) << 8);
            // sweep densities including 0 so genuine zero vectors appear
            let density = (seed % 5) as u32 * 6;
            let v = gen_bitvec(&mut rng, len, density);
            let z = v.is_zero();
            assert_eq!(z, v.count_ones() == 0, "is_zero vs count_ones");
            assert_eq!(z, v.pivot().is_none(), "is_zero vs pivot");
            assert_eq!(z, v.highest_bit().is_none(), "is_zero vs highest_bit");
        }
    }
}

#[test]
fn singleton_has_exactly_one_bit() {
    for &len in BITVEC_LENS {
        if len == 0 {
            continue; // no valid bit index
        }
        for bit in [0, len / 2, len - 1] {
            let v = BitVec::singleton(len, bit);
            assert_eq!(
                v.count_ones(),
                1,
                "singleton popcount (len={len}, bit={bit})"
            );
            assert!(v.get(bit));
            assert_eq!(v.pivot(), Some(bit));
            assert_eq!(v.highest_bit(), Some(bit));
            assert!(!v.is_zero());
            let ones: Vec<usize> = v.ones().collect();
            assert_eq!(ones, vec![bit]);
        }
    }
}

// ---------------------------------------------------------------------------
// BitVec — set / clear / flip
// ---------------------------------------------------------------------------

#[test]
fn flip_is_an_involution_per_bit() {
    for &len in BITVEC_LENS {
        if len == 0 {
            continue;
        }
        for seed in 0..16u64 {
            let mut rng = Rng::new(seed ^ 0xC1 ^ (len as u64) << 8);
            let original = gen_bitvec(&mut rng, len, 24);
            let mut v = original.clone();
            let i = rng.below(len);
            v.flip(i);
            v.flip(i);
            assert_eq!(v, original, "double flip != identity (len={len}, bit={i})");
        }
    }
}

#[test]
fn flip_toggles_exactly_the_target_bit() {
    for &len in BITVEC_LENS {
        if len == 0 {
            continue;
        }
        for seed in 0..16u64 {
            let mut rng = Rng::new(seed ^ 0xD2 ^ (len as u64) << 8);
            let mut v = gen_bitvec(&mut rng, len, 24);
            let i = rng.below(len);
            let before = v.get(i);
            let others_before: Vec<bool> = (0..len).map(|k| v.get(k)).collect();
            v.flip(i);
            assert_eq!(v.get(i), !before, "flip didn't toggle bit {i}");
            for k in 0..len {
                if k != i {
                    assert_eq!(v.get(k), others_before[k], "flip disturbed bit {k}");
                }
            }
        }
    }
}

#[test]
fn set_and_clear_are_idempotent_and_opposite() {
    for &len in BITVEC_LENS {
        if len == 0 {
            continue;
        }
        for seed in 0..16u64 {
            let mut rng = Rng::new(seed ^ 0xE3 ^ (len as u64) << 8);
            let mut v = gen_bitvec(&mut rng, len, 24);
            let i = rng.below(len);

            v.set(i);
            let after_set = v.clone();
            v.set(i);
            assert_eq!(v, after_set, "set is not idempotent");
            assert!(v.get(i));

            v.clear(i);
            let after_clear = v.clone();
            v.clear(i);
            assert_eq!(v, after_clear, "clear is not idempotent");
            assert!(!v.get(i));
        }
    }
}

// ---------------------------------------------------------------------------
// BoundaryMatrix::reduce — structural invariants
// ---------------------------------------------------------------------------

#[test]
fn reduce_is_deterministic() {
    for &(rows, cols, density) in MATRIX_CASES {
        for seed in 0..8u64 {
            let mut rng = Rng::new(seed ^ 0x1234 ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let r1 = m.reduce();
            let r2 = m.reduce();
            for j in 0..cols {
                assert_eq!(
                    r1.matrix.column(j),
                    r2.matrix.column(j),
                    "reduce non-deterministic at col {j} ({rows}x{cols}, seed={seed})"
                );
            }
            assert_eq!(r1.pivot_map, r2.pivot_map, "pivot_map non-deterministic");
        }
    }
}

#[test]
fn reduce_preserves_dimensions() {
    for &(rows, cols, density) in MATRIX_CASES {
        for seed in 0..6u64 {
            let mut rng = Rng::new(seed ^ 0x55AA ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let reduced = m.reduce();
            assert_eq!(reduced.matrix.rows(), rows, "rows changed");
            assert_eq!(reduced.matrix.cols(), cols, "cols changed");
            assert_eq!(reduced.pivot_map.len(), rows, "pivot_map size != rows");
        }
    }
}

#[test]
fn reduced_columns_have_distinct_pivots() {
    // The defining property of a reduced matrix: no two non-zero columns
    // share a pivot (lowest/highest set bit).
    for &(rows, cols, density) in MATRIX_CASES {
        for seed in 0..8u64 {
            let mut rng = Rng::new(seed ^ 0xBEEF ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let reduced = m.reduce();
            let mut seen = BTreeSet::new();
            for j in 0..cols {
                if let Some(p) = reduced.matrix.column_pivot(j) {
                    assert!(
                        seen.insert(p),
                        "duplicate pivot {p} at col {j} ({rows}x{cols}, seed={seed})"
                    );
                }
            }
        }
    }
}

#[test]
fn reduce_is_idempotent() {
    // Reducing an already-reduced matrix must not change any column pivot.
    for &(rows, cols, density) in MATRIX_CASES {
        for seed in 0..8u64 {
            let mut rng = Rng::new(seed ^ 0xF00D ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let once = m.reduce();
            let twice = once.matrix.reduce();
            for j in 0..cols {
                assert_eq!(
                    once.matrix.column_pivot(j),
                    twice.matrix.column_pivot(j),
                    "reduce not idempotent at col {j} ({rows}x{cols}, seed={seed})"
                );
            }
            // A second reduction of a reduced matrix moves nothing at all.
            for j in 0..cols {
                assert_eq!(
                    once.matrix.column(j),
                    twice.matrix.column(j),
                    "reduced column {j} mutated by re-reduction"
                );
            }
        }
    }
}

#[test]
fn pivot_map_round_trips_with_column_pivot() {
    for &(rows, cols, density) in MATRIX_CASES {
        for seed in 0..8u64 {
            let mut rng = Rng::new(seed ^ 0xACE ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let reduced = m.reduce();

            // Every recorded (row -> col) maps back: that column's pivot is `row`.
            let mut mapped_cols = BTreeSet::new();
            for (row, entry) in reduced.pivot_map.iter().enumerate() {
                if let Some(col) = *entry {
                    assert!(col < cols, "pivot_map points to out-of-range col {col}");
                    assert_eq!(
                        reduced.matrix.column_pivot(col),
                        Some(row),
                        "pivot_map[{row}]={col} but column_pivot({col}) disagrees"
                    );
                    assert!(
                        mapped_cols.insert(col),
                        "column {col} claimed by two pivot rows"
                    );
                }
            }
            // Conversely, every non-zero reduced column is registered.
            for j in 0..cols {
                if let Some(p) = reduced.matrix.column_pivot(j) {
                    assert_eq!(
                        reduced.pivot_map[p],
                        Some(j),
                        "non-zero column {j} (pivot {p}) missing from pivot_map"
                    );
                }
            }
        }
    }
}

#[test]
fn zero_columns_stay_zero_through_reduction() {
    for &(rows, cols, density) in MATRIX_CASES {
        for seed in 0..6u64 {
            let mut rng = Rng::new(seed ^ 0x0C0 ^ (rows as u64) << 16 ^ (cols as u64));
            let mut m = gen_matrix(&mut rng, rows, cols, density);
            // Force a couple of columns to zero.
            let zeroed: Vec<usize> = (0..cols).step_by(3).collect();
            for &j in &zeroed {
                *m.column_mut(j) = BitVec::zeros(rows);
            }
            let reduced = m.reduce();
            for &j in &zeroed {
                assert!(
                    reduced.matrix.column(j).is_zero(),
                    "zero column {j} became non-zero after reduction"
                );
                assert_eq!(reduced.matrix.column_pivot(j), None);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Rank invariance — `reduce` is built only from elementary column XORs, so the
// rank (count of non-zero reduced columns) must be invariant under operations
// that span the same column space.
// ---------------------------------------------------------------------------

#[test]
fn rank_is_invariant_under_column_permutation() {
    for &(rows, cols, density) in MATRIX_CASES {
        for seed in 0..10u64 {
            let mut rng = Rng::new(seed ^ 0x9E9E ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let base_rank = rank(&m);

            // Fisher-Yates shuffle the columns.
            let mut cols_vec = columns(&m);
            for i in (1..cols_vec.len()).rev() {
                let j = rng.below(i + 1);
                cols_vec.swap(i, j);
            }
            let permuted = BoundaryMatrix::from_columns(rows, cols_vec);
            assert_eq!(
                rank(&permuted),
                base_rank,
                "rank changed under column permutation ({rows}x{cols}, seed={seed})"
            );
        }
    }
}

#[test]
fn rank_is_invariant_under_elementary_column_xor() {
    // XOR-ing column `src` into a distinct column `dst` is an elementary
    // column operation: it preserves the column space, hence the rank.
    for &(rows, cols, density) in MATRIX_CASES {
        if cols < 2 {
            continue;
        }
        for seed in 0..10u64 {
            let mut rng = Rng::new(seed ^ 0x3711 ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let base_rank = rank(&m);

            let mut mutated = m.clone();
            let dst = rng.below(cols);
            let mut src = rng.below(cols);
            if src == dst {
                src = (src + 1) % cols;
            }
            mutated.xor_columns(dst, src);
            assert_eq!(
                rank(&mutated),
                base_rank,
                "rank changed under elementary column XOR ({rows}x{cols}, seed={seed})"
            );
        }
    }
}

#[test]
fn appending_a_zero_column_does_not_change_rank() {
    for &(rows, cols, density) in MATRIX_CASES {
        for seed in 0..8u64 {
            let mut rng = Rng::new(seed ^ 0x2222 ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let base_rank = rank(&m);

            let mut cols_vec = columns(&m);
            cols_vec.push(BitVec::zeros(rows));
            let extended = BoundaryMatrix::from_columns(rows, cols_vec);
            assert_eq!(
                rank(&extended),
                base_rank,
                "zero column raised rank ({rows}x{cols}, seed={seed})"
            );
        }
    }
}

#[test]
fn duplicating_a_column_does_not_raise_rank() {
    // Appending a copy of an existing column adds a linear dependency, so the
    // rank can only stay the same (it never rises).
    for &(rows, cols, density) in MATRIX_CASES {
        if cols == 0 {
            continue;
        }
        for seed in 0..8u64 {
            let mut rng = Rng::new(seed ^ 0x4D4D ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let base_rank = rank(&m);

            let mut cols_vec = columns(&m);
            let dup = rng.below(cols);
            cols_vec.push(cols_vec[dup].clone());
            let extended = BoundaryMatrix::from_columns(rows, cols_vec);
            assert_eq!(
                rank(&extended),
                base_rank,
                "duplicated column changed rank ({rows}x{cols}, seed={seed})"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// persistence_pairs — structural well-formedness
// ---------------------------------------------------------------------------

#[test]
fn persistence_pairs_are_structurally_well_formed() {
    for &(rows, cols, density) in MATRIX_CASES {
        for seed in 0..10u64 {
            let mut rng = Rng::new(seed ^ 0x7A7A ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let reduced = m.reduce();
            let pp = reduced.persistence_pairs();

            let mut births = BTreeSet::new();
            let mut deaths = BTreeSet::new();
            for &(birth, death) in &pp.pairs {
                assert!(birth < rows, "pair birth {birth} >= rows {rows}");
                assert!(death < cols, "pair death {death} >= cols {cols}");
                assert!(births.insert(birth), "duplicate birth row {birth}");
                assert!(deaths.insert(death), "duplicate death col {death}");
            }
            for &u in &pp.unpaired {
                assert!(u < cols, "unpaired index {u} >= cols {cols}");
                assert!(
                    reduced.matrix.column(u).is_zero(),
                    "unpaired column {u} is not zero"
                );
            }
        }
    }
}

#[test]
fn persistence_pair_count_equals_rank() {
    // Every non-zero reduced column contributes exactly one (pivot, col) pair.
    for &(rows, cols, density) in MATRIX_CASES {
        for seed in 0..10u64 {
            let mut rng = Rng::new(seed ^ 0x6B6B ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, density);
            let r = rank(&m);
            let reduced = m.reduce();
            let pp = reduced.persistence_pairs();
            assert_eq!(
                pp.pairs.len(),
                r,
                "pair count != rank ({rows}x{cols}, seed={seed})"
            );
        }
    }
}

#[test]
fn persistence_pairs_never_panic_on_extreme_shapes() {
    // Stress the rows/cols dimension split that previously caused an
    // out-of-bounds index on non-square matrices.
    let shapes = [
        (1, 64),
        (64, 1),
        (3, 200),
        (200, 3),
        (65, 65),
        (0, 4),
        (4, 0),
    ];
    for &(rows, cols) in &shapes {
        for seed in 0..6u64 {
            let mut rng = Rng::new(seed ^ 0xBAD0 ^ (rows as u64) << 16 ^ (cols as u64));
            let m = gen_matrix(&mut rng, rows, cols, 12);
            let reduced = m.reduce();
            let pp = reduced.persistence_pairs();
            // Total accounted features cannot exceed the column count.
            assert!(
                pp.pairs.len() + pp.unpaired.len() <= cols,
                "feature count exceeds cols for {rows}x{cols}"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// from_columns / accessor round-trips
// ---------------------------------------------------------------------------

#[test]
fn from_columns_round_trips_with_accessors() {
    for &(rows, cols, density) in MATRIX_CASES {
        let mut rng = Rng::new(0xC0FFEE ^ (rows as u64) << 16 ^ (cols as u64));
        let original: Vec<BitVec> = (0..cols)
            .map(|_| gen_bitvec(&mut rng, rows, density))
            .collect();
        let m = BoundaryMatrix::from_columns(rows, original.clone());
        assert_eq!(m.rows(), rows);
        assert_eq!(m.cols(), cols);
        for j in 0..cols {
            assert_eq!(m.column(j), &original[j], "column {j} round-trip");
            for i in 0..rows {
                assert_eq!(
                    m.get(i, j),
                    original[j].get(i),
                    "entry ({i},{j}) round-trip"
                );
            }
        }
    }
}
